name: Code Coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install llvm tools
        run: rustup component add llvm-tools-preview

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Build and Test
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov nextest --no-report --all

          # Room for other test suites types to run here...

      - name: Generate Coverage Report
        run: |
          echo "TOTAL_COV=${cargo llvm-cov report --summary-only | grep 'TOTAL' | awk '{print $4}' }" >> $GITHUB_ENV
          cargo llvm-cov report --html

      - name: Upload coverage to GitHub Actions
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage
          path: coverage

      - name: Post coverage to PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Code coverage for this PR is: $TOTAL_COV"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Coverage generated

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Code coverage for this PR is: ${{ env.TOTAL_COV }}
          edit-mode: replace
          reactions: "eyes"
          
      - name: Zip and Upload Coverage Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-report
          path: target/llvm-cov/html

      - name: Stop the era_test_node
        id: stop_node
        if: always()
        run: |
          yarn dev:kill
