# This workflow is borrowed from reth, which is borrowed from Lighthouse: 
# reth: https://github.com/paradigmxyz/reth/blob/500b0fac135fe07635d871d64467326599e2b27e/.github/workflows/release.yml
# lighthouse: https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/.github/workflows/release.yml

name: release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REPO_NAME: ${{ github.repository_owner }}/era-test-node
  CARGO_TERM_COLOR: always

jobs:
  extract-version:
    name: extract version
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT
        id: extract_version
    outputs:
      VERSION: ${{ steps.extract_version.outputs.VERSION }}

  build:
    name: build release
    strategy:
      matrix:
        # TODO: fix and add aarch64-unknown-linux-gnu target
        # See: https://github.com/matter-labs/era-test-node/issues/56
        arch: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
        include:
          -   arch: x86_64-unknown-linux-gnu
              platform: ubuntu-20.04
          -   arch: x86_64-apple-darwin
              platform: macos-latest
          -   arch: aarch64-apple-darwin
              platform: macos-latest

    runs-on: ${{ matrix.platform }}
    # needs: [extract-version]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Get latest version of stable Rust
        run: rustup update stable
      - name: Install target
        run: rustup target add ${{ matrix.arch }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: false
      - name: Run cargo clean
        run: cargo clean

      # ==============================
      #       Builds
      # ==============================

      - name: Install cross from source
        run: |
          cargo install --git https://github.com/cross-rs/cross cross --branch main

      - name: Build era-test-node for ${{ matrix.arch }}
        run: |
          make build-${{ matrix.arch }}
